site_name: Tyler's TACC Research
docs_dir: docs

theme:
  name: readthedocs

nav:
  - Other:
      - GitHub Repositories: other/githublinks.md
  - TMS:
      - Meeting 1: tms/meeting-1.md
      - Meeting 2: tms/meeting-2.md
      - Meeting 3: tms/meeting-3.md
      - Meeting 4: tms/meeting-4.md
      - Meeting 5: tms/meeting-5.md
      - Meeting 6: tms/meeting-6.md
      - Meeting 7: tms/meeting-7.md
      - Meeting 8: tms/meeting-8.md
      - Meeting 9: tms/meeting-9.md
      - Meeting 10: tms/meeting-10.md
      - Meeting 11: tms/meeting-11.md
      - Meeting 12: tms/meeting-12.md
      - Load Test Results: tms/loadtest_runs.md
  - Tapis Rust SDK and CLI:
      - Loadtest Instructions: tapis/loadtest_instructions.md
      - Tapis CLI: tapis/tapis-cli.md
      - Meeting 1: tapis/meeting-1.md
      - Meeting 2: tapis/meeting-2.md
      - Meeting 3: tapis/meeting-3.md
      - Meeting 4: tapis/meeting-4.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - codehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

